CREATE TABLE contacto (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correo VARCHAR(150) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    asunto VARCHAR(150) NOT NULL,
    comentario TEXT NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;